name: Java CI For Test with Gradle

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    #    services:
    #      docker:
    #        image: docker:dind
    #        options: --privileged
    #        ports:
    #          - 2375:2375

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run Unit Tests
        run: ./gradlew UnitTest

      - name: Run E2E Tests
        run: ./gradlew E2eTest